<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>HealthData.Interop.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="MSTest" Version="3.8.3" />
    <PackageReference Include="FluentAssertions" Version="8.5.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.3" />
    <PackageReference Include="Hl7.Fhir.R4" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\04-Data-Mapping-ETL\04-Data-Mapping-ETL.csproj" />
    <ProjectReference Include="..\05-SMART-on-FHIR\05-SMART-on-FHIR.csproj" />
    <ProjectReference Include="..\03-Resource-Validator\03-Resource-Validator.csproj" />
    <ProjectReference Include="..\HealthData.Interop.Fhir\HealthDataInteropSharedLibrary.csproj" />
    <ProjectReference Include="..\Abstractions\HealthData.Interop.Abstractions\HealthData.Interop.Abstractions.csproj" />
    <ProjectReference Include="..\Logging.Extensions\HealthData.Interop.Logging.Extensions\HealthData.Interop.Logging.Extensions.csproj" />
    <ProjectReference Include="..\Logging.Serilog\HealthData.Interop.Logging.Serilog\HealthData.Interop.Logging.Serilog.csproj" />
  </ItemGroup>

</Project>
