using Hl7.Fhir.Model;
using Riok.Mapperly.Abstractions;

namespace Shared_Library;

/// <summary>
/// [EN] Mapperly-based source generator for converting legacy records to FHIR R4 Patient resources.
/// 
/// Design rationale:
/// - Mapperly generates compile-time code replacing hand-written property copying
/// - Gender normalization centralized via [UserMapping]
/// - Name/Telecom constructed inline via static helpers (two source props -> one FHIR prop)
/// - PostProcess adds Identifier + Meta tags with runtime configuration
/// - Zero reflection overhead — mapping is resolved at compile time
/// 
/// [CN] 基于Mapperly的源代码生成器，将遗留记录转换为FHIR R4 Patient资源。
/// 编译时代码替代手动属性复制。
/// </summary>
[Mapper]
public partial class FhirPatientMapper
{
    public const string DefaultIdSystem = "http://example.org/test-ids";
    public const string UsCorePatientProfile = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient";

    private readonly string _idSystem;
    private readonly bool _usCoreProfile;
    private readonly bool _addTestDataTag;
    private readonly bool _testNameMarkers;

    /// <summary>
    /// [EN] Create a new FhirPatientMapper with the specified configuration.
    /// [CN] 使用指定配置创建新的FhirPatientMapper。
    /// </summary>
    /// <param name="idSystem">[EN] Identifier system URI / [CN] 标识符系统URI</param>
    /// <param name="usCoreProfile">[EN] Whether to add US Core profile / [CN] 是否添加US Core配置档</param>
    /// <param name="addTestDataTag">[EN] Whether to add test-data Meta tag / [CN] 是否添加测试数据Meta标签</param>
    /// <param name="testNameMarkers">[EN] Whether MapLegacy appends "-Test"/"[TEST]" name markers (module 04 sandbox convention) / [CN] MapLegacy是否为姓名追加"-Test"/"[TEST]"测试标记（模块04沙盒约定）</param>
    public FhirPatientMapper(
        string? idSystem = null,
        bool usCoreProfile = false,
        bool addTestDataTag = true,
        bool testNameMarkers = false)
    {
        _idSystem = string.IsNullOrWhiteSpace(idSystem) ? DefaultIdSystem : idSystem;
        _usCoreProfile = usCoreProfile;
        _addTestDataTag = addTestDataTag;
        _testNameMarkers = testNameMarkers;
    }

    /// <summary>
    /// [EN] Map LegacyPatientRecord (module 04 CSV) to FHIR Patient.
    /// [CN] 将LegacyPatientRecord映射到FHIR Patient。
    /// </summary>
    public virtual Patient MapLegacy(LegacyPatientRecord source)
    {
        Guard.NotNull(source, nameof(source));

        var patient = MapToPatient(source);
        patient.Name = new List<HumanName> { BuildHumanName(source.FirstName, source.LastName, _testNameMarkers) };
        patient.Telecom = BuildTelecom(source.Phone);
        PostProcess(patient, source.Id);
        return patient;
    }

    /// <summary>
    /// [EN] Full pipeline for RawPatientData (module 05).
    /// [CN] 完整流水线，将RawPatientData映射为FHIR Patient。
    /// </summary>
    public virtual Patient MapRaw(RawPatientData source)
    {
        Guard.NotNull(source, nameof(source));

        var patient = MapToPatient(source);
        // [EN] Module 05 marks imported patients as Active (preserved from pre-refactor behavior).
        // [CN] 模块05将导入的患者标记为Active（保持重构前的行为）。
        patient.Active = true;
        patient.Name = new List<HumanName> { BuildHumanName(source.FirstName, source.LastName) };
        var legacyId = $"{source.FirstName.Trim()}_{source.LastName.Trim()}";
        PostProcess(patient, legacyId);
        return patient;
    }

    // ====== Mapperly generated mapping (Gender + BirthDate only) ======

    /// <summary>
    /// [EN] Generated by Mapperly. Maps Gender (via UserMapping) and BirthDate from LegacyPatientRecord.
    /// [CN] 由Mapperly生成。映射LegacyPatientRecord的性别和出生日期。
    /// </summary>
    private partial Patient MapToPatient(LegacyPatientRecord source);

    /// <summary>
    /// [EN] Generated by Mapperly. Maps Gender (via UserMapping) and BirthDate from RawPatientData.
    /// [CN] 由Mapperly生成。映射RawPatientData的性别和出生日期。
    /// </summary>
    private partial Patient MapToPatient(RawPatientData source);

    // ====== [UserMapping] for gender normalization (centralized) ======

    /// <summary>
    /// [EN] User-defined mapping: raw gender string -> AdministrativeGender enum.
    /// [CN] 用户自定义映射：原始性别字符串->AdministrativeGender枚举。
    /// </summary>
    [UserMapping]
    public static AdministrativeGender MapGender(string gender)
    {
        return GenderNormalizer.Normalize(gender);
    }

    // ====== Post-processing (runtime config injection) ======

    /// <summary>
    /// [EN] Attach Identifier with configurable system URI and optional US Core / test-data Meta.
    /// [CN] 附加标识符和可选US Core/测试数据Meta。
    /// </summary>
    public virtual void PostProcess(Patient patient, string legacyId)
    {
        Guard.NotNull(patient, nameof(patient));
        Guard.NotNullOrEmpty(legacyId, nameof(legacyId));

        patient.Identifier ??= new List<Identifier>();
        patient.Identifier.Add(new Identifier(_idSystem, legacyId));

        var tags = new List<Coding>();
        if (_addTestDataTag)
        {
            tags.Add(new Coding(
                system: "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
                code: "SUBSET",
                display: "Test Data"));
        }

        if (patient.Meta is null)
            patient.Meta = new Meta();

        var existingTags = patient.Meta.Tag?.ToList() ?? new List<Coding>();
        patient.Meta.Tag = existingTags.Concat(tags).ToList();

        if (_usCoreProfile)
        {
            var profiles = patient.Meta.Profile;
            var existingProfiles = new List<string>();
            foreach (var p in profiles ?? Enumerable.Empty<string>())
                if (!string.IsNullOrEmpty(p))
                    existingProfiles.Add(p);
            if (!existingProfiles.Contains(UsCorePatientProfile))
                existingProfiles.Add(UsCorePatientProfile);
            patient.Meta.Profile = existingProfiles;
        }
    }

    // ====== Static helpers (unit-testable, reusable) ======

    /// <summary>
    /// [EN] Build a FHIR HumanName with trimmed name parts. When <paramref name="testMarkers"/>
    /// is true, appends the module 04 sandbox markers ("-Test" to given, " [TEST]" to family)
    /// so test data is easy to spot on the shared public FHIR server.
    /// [CN] 构建带有修剪后的姓名的FHIR HumanName。testMarkers为true时追加模块04的沙盒标记
    /// （名字加"-Test"、姓氏加" [TEST]"），便于在共享公共FHIR服务器上识别测试数据。
    /// </summary>
    public static HumanName BuildHumanName(string firstName, string lastName, bool testMarkers = false)
    {
        var given = firstName.Trim();
        var family = lastName.Trim();

        if (testMarkers)
        {
            given += "-Test";
            family += " [TEST]";
        }

        return new HumanName
        {
            Given = new[] { given },
            Family = family
        };
    }

    /// <summary>
    /// [EN] Build a List<ContactPoint> from a phone number. Returns null for empty input.
    /// [CN] 从电话号码构建List<ContactPoint>。空输入返回null。
    /// </summary>
    public static List<ContactPoint>? BuildTelecom(string? phone)
    {
        if (string.IsNullOrWhiteSpace(phone))
            return null;

        return new List<ContactPoint>
        {
            new ContactPoint(
                system: ContactPoint.ContactPointSystem.Phone,
                use: null,
                value: phone.Trim())
        };
    }
}
